### ISSUE TITLE
Error when making doc

### ISSUE THREAD

**Issue by LumenYoung** [YangLiu9208/CausalVLR#1]
Hi, 

Thank you for your great work. I'm actually trying to get detailed information on the project by reading documentation. But I find it a bit complicated because either compile as html or latexpdf don't work on my PC.

I get the following error message when using `make html` in `docs` folder:

```
❯ make html
Running Sphinx v7.1.2
WARNING: html_static_path entry '_static' does not exist
loading pickled environment... done

Theme error:
no theme named 'press' found (missing theme.conf?)
make: *** [Makefile:20: html] Error 2
```

And following message for `make latexpdf`:

```
❯ make latexpdf
Running Sphinx v7.1.2
WARNING: html_static_path entry '_static' does not exist
loading pickled environment... failed
failed: Can't get attribute '_stable_repr_object' on <module 'sphinx.builders.html' from '/home/yang/.local/pipx/venvs/sphinx/lib/python3.11/site-packages/sphinx/builders/html/__init__.py'>
building [mo]: targets for 0 po files that are out of date
writing output...
building [latex]: all documents
updating environment: [new config] 1 added, 0 changed, 0 removed
reading sources... [100%] index
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
copying TeX support files... copying TeX support files...
done
processing causal-vlreasoning.tex... index
resolving references...
done
writing... done
build succeeded, 1 warning.

The LaTeX files are in build/latex.
Run 'make' in that directory to run these through (pdf)latex
(use `make latexpdf' here to do that automatically).
make[1]: Entering directory '/home/yang/Documents/git/CausalVLR/docs/build/latex'
latexmk -pdf -dvi- -ps-  'causal-vlreasoning.tex'
make[1]: latexmk: No such file or directory
make[1]: *** [Makefile:29: causal-vlreasoning.pdf] Error 127
make[1]: Leaving directory '/home/yang/Documents/git/CausalVLR/docs/build/latex'
make: *** [Makefile:20: latexpdf] Error 2
```

Could you please provide detailed instruction for compiling the documentation? Thanks

**Comment by LumenYoung** [comment]
To avoid any confusion. I'm referring to the forked repo [here](https://github.com/HCPLab-SYSU/CausalVLR).

But since it is a forked repo, there is no issue section available for that. Therefore I leave  the issue here. I would apologize if it is not the appropriate place to file an isssue.

**Comment by YangLiu9208** [comment]
Thanks a lot for your interest. We have opened the isssue section in https://github.com/HCPLab-SYSU/CausalVLR. The main page is still https://github.com/HCPLab-SYSU/CausalVLR. Our CausalVLR is actively updating, please stay tuned.
